[game]
hostname = "üåü Corvax ‚Äî –í–µ–≥–∞ SandBox üåü[18+]"
desc = "–ö–æ—Ä–≤–∞–∫—Å ‚Äî –ø–µ—Ä–≤—ã–π —Ä—É—Å—Å–∫–æ—è–∑—ã—á–Ω—ã–π –ø—Ä–æ–µ–∫—Ç –≤ Space Station 14.\n–í–µ–≥–∞ ‚Äî —ç—Ç–æ –ø–µ—Ä–≤—ã–π –æ—Ñ–∏—Ü–∏–∞–ª—å–Ω—ã–π –ï–†–ü —Å–µ—Ä–≤–µ—Ä –æ—Ç –ö–æ—Ä–≤–∞–∫—Å!\n–ï–†–ü —è–≤–ª—è–µ—Ç—Å—è –ª–∏—à—å –¥–æ–ø—É—Å—Ç–∏–º–æ–π –æ–ø—Ü–∏–µ–π, –∞ –Ω–µ –∑–∞–º–µ–Ω—è—é—â–µ–π —á–∞—Å—Ç—å—é –≥–µ–π–º–ø–ª–µ—è."
map_pool = "WegaDefaultMapPool"
fallbackpreset = "sandbox"
maxplayers = 60
soft_max_players = 40
map_rotation = false

[net]
tickrate = 30

[netres]
limit = 25.0

[viewport]
maximum_width = 26

[admin]
admins_count_in_playercount = true

[game.panic_bunker]
enabled = true
show_reason = true
min_account_age = 99999
min_overall_minutes = 0

[hub]
advertise = false
tags = "lang:ru,rp:low,rp:med,region:eu_e,18+"

[server]
lobby_name = "üåü Corvax ‚Äî –í–µ–≥–∞ SandBox üåü[18+]"

[shuttle]
arrivals_map = "/Maps/Corvax/Misc/corvax_terminal.yml"
