[game]
hostname = "üåü Corvax ‚Äî –í–µ–≥–∞ üåü[18+]"
desc = "–ö–æ—Ä–≤–∞–∫—Å ‚Äî –ø–µ—Ä–≤—ã–π —Ä—É—Å—Å–∫–æ—è–∑—ã—á–Ω—ã–π –ø—Ä–æ–µ–∫—Ç –≤ Space Station 14.\n–í–µ–≥–∞ ‚Äî —ç—Ç–æ –ø–µ—Ä–≤—ã–π –æ—Ñ–∏—Ü–∏–∞–ª—å–Ω—ã–π –ï–†–ü —Å–µ—Ä–≤–µ—Ä –æ—Ç –ö–æ—Ä–≤–∞–∫—Å!\n–ï–†–ü —è–≤–ª—è–µ—Ç—Å—è –ª–∏—à—å –¥–æ–ø—É—Å—Ç–∏–º–æ–π –æ–ø—Ü–∏–µ–π, –∞ –Ω–µ –∑–∞–º–µ–Ω—è—é—â–µ–π —á–∞—Å—Ç—å—é –≥–µ–π–º–ø–ª–µ—è."
map_pool = "WegaDefaultMapPool"
secret_weight_prototype = "WegaSecretDefault"
maxplayers = 180
soft_max_players = 100
lobbyduration = 360
map_rotation = false

[wega]
respawn_enabled = true
barks_enabled = true
night_light_enabled = true

[net]
tickrate = 30

[netres]
limit = 25.0

[admin]
admins_count_in_playercount = true

[movement]
mob_pushing = false

[infolinks]
discord = "https://discord.gg/bJrgSmKf3a"
wiki = "https://station14.ru"
appeal = "https://discord.gg/bJrgSmKf3a"
website = "https://ss14.ru"

[viewport]
maximum_width = 26

[game.panic_bunker]
enabled = true
show_reason = true
min_account_age = 0
min_overall_minutes = 0
deny_vpn = true
enable_without_admins = true
disable_with_admins = true

[rules]
time = 180.0

[hub]
advertise = true
tags = "lang:ru,rp:low,rp:med,region:eu_e,18+"

[server]
lobby_name = "üåü Corvax ‚Äî –í–µ–≥–∞ üåü[18+]"
rules_file = "WegaRuleset"

[atmos]
max_explosion_range = 5
space_wind = true

[shuttle]
emergency_early_launch_allowed = true
arrivals_map = "/Maps/Corvax/Misc/corvax_terminal.yml"
auto_call_time = 150

[vote]
preset_enabled = true
map_enabled = true
