- type: playTimeTracker
  id: JobBarber

- type: playTimeTracker
  id: JobCBURNLeader

- type: playTimeTracker
  id: JobGeneticist

- type: playTimeTracker
  id: JobSurgeon

- type: playTimeTracker
  id: JobCoroner

- type: playTimeTracker
  id: JobBlueShield
