name: "Labels: Untriaged"

on:
  issues:
    types: [opened]
  pull_request_target:
    types: [opened]

jobs:
  add_label:
    runs-on: ubuntu-latest
    steps:
      - name: Add label to issue
        if: github.event_name == 'issues' && join(github.event.issue.labels.*.name) == ''
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: "S: Untriaged"

      - name: Add label to pull request
        if: github.event_name == 'pull_request_target' && join(github.event.pull_request.labels.*.name) == ''
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: "S: Untriaged"
